### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by 50l3r** [avil13/vue-sweetalert2#48]
I try to use vue-sweetalert2 in my project:

```
import VueSweetalert2 from 'vue-sweetalert2';
Vue.use(VueSweetalert2);
```

But i recieve this error:

```
\node_modules\vue-sweetalert2\src\index.js:3 Uncaught SyntaxError: Unexpected token import
    at createScript (vm.js:80)
    at Object.runInThisContext (vm.js:139)
    at Module._compile (module.js:606)
    at Object.Module._extensions..js (module.js:653)
    at Module.load (module.js:561)
    at tryModuleLoad (module.js:504)
    at Function.Module._load (module.js:496)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at eval (external "vue-sweetalert2"?cfeb:1)
```

**Comment by 50l3r** [comment]
I solved it adding sweetalert2 package to vue prototype

```
import Swal from 'sweetalert2';
Vue.prototype.$swal = Swal;
```

**Comment by avil13** [comment]
```
import VueSweetalert2 from 'vue-sweetalert2';
Vue.use(VueSweetalert2);
```
@50l3r  Can you tell what is your version of Vue?

I want to try to get the same error but everything works.

**Comment by 50l3r** [comment]
I use vue 2.6.7

**Comment by avil13** [comment]
@50l3r
You want to try this version. If all right, then I will update.

 `npm i vue-sweetalert2@beta`

**Comment by avil13** [comment]
fixed in v2.
Update package `npm i vue-sweetalert2`

**Comment by andrewrusselrenner** [comment]
I still have this issue on vue2 with electron, even adding sweetalert2 package to vue prototype :(
![image](https://user-images.githubusercontent.com/5303871/96371980-3b721c00-1197-11eb-92f5-c9058dc64da3.png)

**Comment by avil13** [comment]
You probably do not have an assembly stage.
For example, via webpack.
